### PR TITLE
Issue 91 - Allow disabling builtin functions

### PR DESCRIPTION
**Pull request by dktcoding**
The rest of the implementation of Issue 91 isn't as straight forward because it was based on an incorrect implementation of disable implicit multiplication. I will create a new issue in this fork to test if it's possible to make it work properly.

@njdoyle: perhaps this is something like you were asking.

### CODE REVIEW

**Comment by dktcoding** [comment]
A usage example of this is: 

```java
    Expression e = new ExpressionBuilder("sin(x)")
                      .disableBuiltInFunctions()
                      .function(Functions.getBuiltinFunction("sin"))
                      .variable("x")
                      .build();
```

So basically you are able of rejecting all builtin functions and then add the ones you want.

**Comment by njdoyle** [comment]
I gave the code a quick skim and it looks like it would mostly fit my use case.

If I were to implement this personally, I would take kind of a reversed approach where each builtin function/operator is explicitly added the same way a user function would be added. On construction of an expression, these builtins would be added automatically unless we specifically disabled builtins. This way, there's no real special case for builtins versus user functions. This probably has implications for implied multiplication. I personally would disable implied multiplication for my use case. Perhaps an empty string operator could be used for implied (multiplication) operator?

The pattern for re-adding builtins you used in your example is pretty much exactly what I was looking for as my whitelist functionality.

**Comment by dktcoding** [comment]
> If I were to implement this personally, I would take kind of a reversed approach where each builtin function/operator is explicitly added the same way a user function would be added.

This might be a nicer approach for your specific case, but it will most certainly break things for 99% of the current user base.

> On construction of an expression, these builtins would be added automatically unless we specifically disabled builtins.

This is exactly what's going on now, but with all the builtins (current implementation doesn't make it easy to flag specific functions and operators).

>  I personally would disable implied multiplication for my use case. Perhaps an empty string operator could be used for implied (multiplication) operator?

Implied multiplication is sort of a controversial feature, caused a lot problems, but was also one of the most requested features (personally, I can't live without it). 

My problem with this is that I checked the implementation of 499418fcd998f1155c9242ebc2b1baa514f54ec1 and found a lot of errors when testing simple cases like:

```java
    Expression e = new ExpressionBuilder("x2")
                      . implicitMultiplication(false)
                      .variable("x")
                      .build(); //<-- This should fail
```

Please note that this is a modified version of `exp4j` ([changes](https://github.com/RiddlerArgentina/exp4j/wiki/Differences-with-the-original-exp4j)) so it's probable that the approach on 499418fcd998f1155c9242ebc2b1baa514f54ec1 works fine, but it's incompatible with this fork.

I will attempt to create a `Expression#disableImplicitMultiplication()` method later, but it will have to wait a bit (or you could implement it yourself! I will accept any changes that are thoroughly tested and don't break any of the existing tests).

> Maybe having static final constants to get the functions instead of getBuiltinFunction would make the builtins more discoverable instead of needing to know the string to pass as a parameter.

This is actually something that crossed my mind of a couple of years ago, then Java 7 came out with support for using strings in switch and... well it didn't matter much. Of course there's another alternative, disable all the functions, and create a `MyCustomFunctionListClass` that handles all the flagging in the way that's most convenient to your project then simply add a method that returns a `List<Function>` with the ones you want.

**Comment by eduSnows** [comment]
> Of course there's another alternative, disable all the functions, and create a MyCustomFunctionListClass that handles all the flagging in the way that's most convenient to your project then simply add a method that returns a List<Function> with the ones you want.

This seems to be the most apropiate approach

**Comment by njdoyle** [comment]
I should clarify the builtin approach I meant because I don't think I made my idea as clear as it could be. The functionality from the outside is pretty much the same as your example. The difference is under the hood.
What I'm suggesting is that builtin handling would be done by the `ExpressionBuilder` instead of the `Tokenizer`. By default, functionally the `ExpressionBuilder` would basically have a bunch of implied calls to its `function` method with the builtin functions which would be loaded in to what is currently called `Tokenizer.userFunctions`. If `ExpressionBuilder.disableBuiltInFunctions` is called, it becomes simply the case that those implied calls to `ExpressionBuilder.function` don't get called. This keeps the special cases out of places like `Tokenizer.getFunction` and have a more unified structure.

**Comment by njdoyle** [comment]
With regards to the static Strings for the builtin function names. What I'm getting at is making the Strings that are used literally in `Functions.getBuiltinFunction` and move them out in to public static String constants. This makes it so that a user of the library can easily discover what builtins are available through code-completion or looking at what's exposed by a (potentially compiled) class instead of needing to dig in to the source. This or expose the literal `Function` instances in a similar way for a more direct approach.

**Comment by dktcoding** [comment]
> What I'm suggesting is that builtin handling would be done by the `ExpressionBuilder` instead of the `Tokenizer`.

> This keeps the special cases out of places like `Tokenizer.getFunction` and have a more unified structure.

This seems like a good idea, but I'm fairly certain that will require some work on the `Tokenizer` (I'll take a look at it), the `Tokenizer` was written by @fasseg and since it worked very well we never really look at it twice. 

> This makes it so that a user of the library can easily discover what builtins are available through code-completion

This actually sounds good I'll add it to this same branch in a moment and tell me what you think

**Comment by dktcoding** [comment]
> Yeah, I like the change to make the functions more discoverable.

Great I'll merge and update now! Downloads should appear [here](https://github.com/RiddlerArgentina/exp4j/wiki).

> Neither of those objects should really need to know about builtin functions to perform their duties.

That's true, unfortunately I gave a quick glance at the code and this is not true for the operators

**Comment by dktcoding** [comment]
Ok... `travis-ci` seems to be experiencing some technical difficulties with `Jacoco`.

 `jars` were built and tests passed, but I'll postpone the merge until tests are officially done.

**Pull request merged**
